# This file defines Render deployment configuration

services:
  - type: web  # web service type
    name: shoppers-intent-mlops  # service name on render
    env: docker  # use docker for deployment
    dockerfilePath: ./Dockerfile  # path to dockerfile
    plan: free  # render free tier
    region: oregon  # render region
    branch: main  # deploy from main branch

    envVars:
      - key: MODEL_PATH
        value: /app/ml/model.pkl  # model save path

      - key: MLFLOW_TRACKING_URI
        value: /app/mlruns  # mlflow tracking uri

